name: 'zendesk_cx'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dbt-cloud:
  project-id: 70471823585824

on-run-start:
  - "{{ create_zendesk_masking_policies() }}"

models:
  zendesk_cx:
    staging:
      +materialized: view
    marts:
      +materialized: table
      cx:
        fct_tickets:
          +materialized: incremental
          +unique_key: ticket_id
        fct_ticket_events:
          +materialized: incremental
          +unique_key: [id, field_name]
        fct_ticket_comments:
          +materialized: incremental
          +unique_key: id

seeds:
  zendesk_cx:
    +quote_columns: false

vars:
  zendesk_use_seeds: true
