-- ============================================================
-- PIPELINE: S3 → WILD_CARD.BRONZE (Zendesk)
-- ============================================================

-- ------------------------------------------------------------
-- 1. FILE FORMAT
-- ------------------------------------------------------------
CREATE OR REPLACE FILE FORMAT WILD_CARD.BRONZE.ZENDESK_PARQUET
  TYPE               = PARQUET
  SNAPPY_COMPRESSION = TRUE
  NULL_IF            = ();

-- ------------------------------------------------------------
-- 2. EXTERNAL STAGE (Histórico - Datalake)
-- ------------------------------------------------------------
CREATE OR REPLACE STAGE WILD_CARD.BRONZE.ZENDESK_S3_DATALAKE
  URL                  = 's3://<YOUR_S3_DATALAKE_BUCKET>/bronze/zendesk/'
  STORAGE_INTEGRATION  = S3_INTEGRATION_<YOUR_DATALAKE>
  FILE_FORMAT          = WILD_CARD.BRONZE.ZENDESK_PARQUET;

-- ------------------------------------------------------------
-- 2.1 EXTERNAL STAGE (Incremental - Datamesh)
-- ------------------------------------------------------------
CREATE OR REPLACE STAGE WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH
  URL                  = 's3://<YOUR_S3_DATAMESH_BUCKET>/wild_card/zendesk/'
  STORAGE_INTEGRATION  = S3_INTEGRATION_<YOUR_DATAMESH>
  FILE_FORMAT          = WILD_CARD.BRONZE.ZENDESK_PARQUET
  DIRECTORY            = (ENABLE = TRUE);

-- ============================================================
-- 3. TABELAS BRONZE
-- ============================================================

-- 3.1 Groups
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_GROUPS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.2 Organizations
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_ORGANIZATIONS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.3 Ticket Fields
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_TICKET_FIELDS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.4 Ticket Metrics
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_TICKET_METRICS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.4.1 Ticket Metrics FULL (snapshot agregado via /incremental/tickets?include=metric_sets)
-- Substitui parcialmente o ZENDESK_TICKET_METRICS quanto a reply_time_in_minutes,
-- agent_wait_time_in_minutes e demais campos agregados que o
-- /incremental/ticket_metric_events.json deixou de retornar em 2026-05-04.
CREATE TABLE IF NOT EXISTS WILD_CARD.BRONZE.ZENDESK_TICKET_METRICS_FULL (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.5 Tickets
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_TICKETS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.6 Tickets Events
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_TICKETS_EVENTS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- 3.7 Users
CREATE OR REPLACE TABLE WILD_CARD.BRONZE.ZENDESK_USERS (
  RAW_DATA             VARIANT,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('America/Sao_Paulo', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
);

-- ============================================================
-- 4. PIPES (AUTO_INGEST do Stage Datamesh - incremental)
-- ============================================================

-- 4.1 Groups
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_GROUPS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_GROUPS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/groups/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.2 Organizations
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_ORGANIZATIONS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_ORGANIZATIONS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/organizations/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.3 Ticket Fields
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_TICKET_FIELDS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_TICKET_FIELDS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/ticketFields/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.4 Ticket Metrics
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_TICKET_METRICS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_TICKET_METRICS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/ticketMetrics/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.4.1 Ticket Metrics FULL (snapshot agregado)
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_TICKET_METRICS_FULL_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_TICKET_METRICS_FULL (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/ticketMetricsFull/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.5 Tickets
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_TICKETS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_TICKETS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/tickets/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.6 Tickets Events
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_TICKETS_EVENTS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_TICKETS_EVENTS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/tickets_events/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- 4.7 Users
CREATE OR REPLACE PIPE WILD_CARD.BRONZE.ZENDESK_USERS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO WILD_CARD.BRONZE.ZENDESK_USERS (RAW_DATA)
FROM (SELECT $1 FROM @WILD_CARD.BRONZE.ZENDESK_S3_DATAMESH/users/)
FILE_FORMAT = (FORMAT_NAME = 'WILD_CARD.BRONZE.ZENDESK_PARQUET')
ON_ERROR    = CONTINUE;

-- ============================================================
-- 5. CONFIGURAÇÃO SNS (Snowpipe Auto-Ingest)
-- ============================================================
-- Execute SHOW PIPES IN SCHEMA WILD_CARD.BRONZE para obter o ARN da
-- notificação SQS de cada pipe. Configure o evento S3 (s3:ObjectCreated:*)
-- no bucket Datamesh com prefixo wild_card/zendesk/{entidade}/
-- para enviar ao ARN correspondente.
