-- ============================================================
-- GOLD: CX.SILVER → CX.GOLD (Zendesk)
-- Sem colunas PII (DESCRIPTION removida, SUBJECT mascarado)
-- Apenas ZENDESK_TICKETS e ZENDESK_USERS
-- ============================================================

-- ============================================================
-- 1. TABELAS GOLD
-- ============================================================
-- ------------------------------------------------------------
-- 1.1 Tickets (sem DESCRIPTION, SUBJECT com masking)
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_TICKETS (
  ID                                NUMBER,
  SUBJECT                           STRING,
  STATUS                            STRING,
  PRIORITY                          STRING,
  BRAND_ID                          NUMBER,
  ASSIGNEE_ID                       NUMBER,
  REQUESTER_ID                      NUMBER,
  SUBMITTER_ID                      NUMBER,
  ORGANIZATION_ID                   NUMBER,
  GROUP_ID                          NUMBER,
  TICKET_FORM_ID                    NUMBER,
  VIA                               STRING,
  TAGS                              STRING,
  SATISFACTION_RATING               STRING,
  IS_PUBLIC                         BOOLEAN,
  HAS_INCIDENTS                     BOOLEAN,
  FROM_MESSAGING_CHANNEL            BOOLEAN,
  CF_ACIONAR_CONTABILIDADE          STRING,
  CF_MOTIVO_DE_CONTATO              STRING,
  CF_TAG_DE_ATENDIMENTO             STRING,
  CF_TAG_DE_ATENDIMENTO_2           STRING,
  CF_ADICIONAR_SEGUNDO_PERIODO_FERIAS STRING,
  CF_ADICIONAR_TERCEIRO_PERIODO_FERIAS STRING,
  CF_CONVERSATION_ID                STRING,
  CF_HSM_DATA                       STRING,
  CF_HSM_DESCRICAO_TEMPLATE         STRING,
  CF_HSM_STATUS                     STRING,
  CF_HSM_TEMPLATE                   STRING,
  CF_WHATSAPP_ID                    STRING,
  CF_MIGRACAO_DE_AREA               STRING,
  CF_TAG_DE_ATENDIMENTO_3           STRING,
  CF_RENOVOU_CERTIFICADO_ECNPJ      STRING,
  CF_ATRIBUICAO_AUTOMATICA          STRING,
  CF_PIECE_OF_CAKE_DISPARO          STRING,
  CUSTOM_FIELDS_JSON                STRING,
  REOPENS                           NUMBER,
  REPLIES                           NUMBER,
  ASSIGNEE_STATIONS                 NUMBER,
  GROUP_STATIONS                    NUMBER,
  AGENT_WAIT_TIME_IN_MINUTES        STRING,
  REQUESTER_WAIT_TIME_IN_MINUTES    STRING,
  FIRST_RESOLUTION_TIME_IN_MINUTES  STRING,
  FULL_RESOLUTION_TIME_IN_MINUTES   STRING,
  ON_HOLD_TIME_IN_MINUTES           STRING,
  REPLY_TIME_IN_MINUTES             STRING,
  ASSIGNED_AT                       TIMESTAMP_NTZ,
  INITIALLY_ASSIGNED_AT             TIMESTAMP_NTZ,
  SOLVED_AT                         TIMESTAMP_NTZ,
  LATEST_COMMENT_ADDED_AT           TIMESTAMP_NTZ,
  CREATED_AT                        TIMESTAMP_NTZ,
  UPDATED_AT                        TIMESTAMP_NTZ,
  DATALAKE_UPDATED_AT               TIMESTAMP_NTZ,
  _SNOWFLAKE_LOADED_AT              TIMESTAMP_NTZ
);

-- ------------------------------------------------------------
-- 1.2 Users (sem NAME, sem EMAIL)
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_USERS (
  ID                   NUMBER,
  ROLE                 STRING,
  LOCALE               STRING,
  TIME_ZONE            STRING,
  TAGS                 STRING,
  ACTIVE               BOOLEAN,
  VERIFIED             BOOLEAN,
  SUSPENDED            BOOLEAN,
  MODERATOR            BOOLEAN,
  RESTRICTED_AGENT     BOOLEAN,
  SHARED               BOOLEAN,
  SHARED_AGENT         BOOLEAN,
  TICKET_RESTRICTION   STRING,
  CREATED_AT           TIMESTAMP_NTZ,
  UPDATED_AT           TIMESTAMP_NTZ,
  DATALAKE_UPDATED_AT  TIMESTAMP_NTZ,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ
);

-- Masking policy para SUBJECT na Gold
CREATE OR REPLACE MASKING POLICY CX.GOLD.MASK_ZENDESK_TICKET_SUBJECT_PII
  AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_CX', 'ROLE_DOMAIN_CX_PII', 'ACCOUNTADMIN')
      THEN val
    ELSE LEFT(val, 4) || REPEAT('*', GREATEST(LENGTH(val) - 4, 0))
  END;

ALTER TABLE CX.GOLD.ZENDESK_TICKETS MODIFY COLUMN SUBJECT
  SET MASKING POLICY CX.GOLD.MASK_ZENDESK_TICKET_SUBJECT_PII;

-- ============================================================
-- 2. PROCEDURES DE CARGA
-- ============================================================
-- ------------------------------------------------------------
-- 2.1 Tickets
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CX.GOLD.ZENDESK_TICKETS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CX.GOLD.ZENDESK_TICKETS tgt
  USING (
    SELECT
      ID, SUBJECT, STATUS, PRIORITY, BRAND_ID, ASSIGNEE_ID, REQUESTER_ID,
      SUBMITTER_ID, ORGANIZATION_ID, GROUP_ID, TICKET_FORM_ID, VIA, TAGS,
      SATISFACTION_RATING, IS_PUBLIC, HAS_INCIDENTS, FROM_MESSAGING_CHANNEL,
      CF_ACIONAR_CONTABILIDADE, CF_MOTIVO_DE_CONTATO, CF_TAG_DE_ATENDIMENTO, CF_TAG_DE_ATENDIMENTO_2,
      CF_ADICIONAR_SEGUNDO_PERIODO_FERIAS, CF_ADICIONAR_TERCEIRO_PERIODO_FERIAS,
      CF_CONVERSATION_ID, CF_HSM_DATA, CF_HSM_DESCRICAO_TEMPLATE, CF_HSM_STATUS, CF_HSM_TEMPLATE,
      CF_WHATSAPP_ID, CF_MIGRACAO_DE_AREA, CF_TAG_DE_ATENDIMENTO_3, CF_RENOVOU_CERTIFICADO_ECNPJ,
      CF_ATRIBUICAO_AUTOMATICA, CF_PIECE_OF_CAKE_DISPARO, CUSTOM_FIELDS_JSON,
      REOPENS, REPLIES, ASSIGNEE_STATIONS, GROUP_STATIONS,
      AGENT_WAIT_TIME_IN_MINUTES, REQUESTER_WAIT_TIME_IN_MINUTES,
      FIRST_RESOLUTION_TIME_IN_MINUTES, FULL_RESOLUTION_TIME_IN_MINUTES,
      ON_HOLD_TIME_IN_MINUTES, REPLY_TIME_IN_MINUTES,
      ASSIGNED_AT, INITIALLY_ASSIGNED_AT, SOLVED_AT, LATEST_COMMENT_ADDED_AT,
      CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT
    FROM CX.SILVER.ZENDESK_TICKETS WHERE ID IS NOT NULL
  ) src ON tgt.ID = src.ID

  WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
    SUBJECT = src.SUBJECT, STATUS = src.STATUS, PRIORITY = src.PRIORITY, BRAND_ID = src.BRAND_ID,
    ASSIGNEE_ID = src.ASSIGNEE_ID, REQUESTER_ID = src.REQUESTER_ID, SUBMITTER_ID = src.SUBMITTER_ID,
    ORGANIZATION_ID = src.ORGANIZATION_ID, GROUP_ID = src.GROUP_ID, TICKET_FORM_ID = src.TICKET_FORM_ID,
    VIA = src.VIA, TAGS = src.TAGS, SATISFACTION_RATING = src.SATISFACTION_RATING,
    IS_PUBLIC = src.IS_PUBLIC, HAS_INCIDENTS = src.HAS_INCIDENTS, FROM_MESSAGING_CHANNEL = src.FROM_MESSAGING_CHANNEL,
    CF_ACIONAR_CONTABILIDADE = src.CF_ACIONAR_CONTABILIDADE, CF_MOTIVO_DE_CONTATO = src.CF_MOTIVO_DE_CONTATO,
    CF_TAG_DE_ATENDIMENTO = src.CF_TAG_DE_ATENDIMENTO, CF_TAG_DE_ATENDIMENTO_2 = src.CF_TAG_DE_ATENDIMENTO_2,
    CF_ADICIONAR_SEGUNDO_PERIODO_FERIAS = src.CF_ADICIONAR_SEGUNDO_PERIODO_FERIAS,
    CF_ADICIONAR_TERCEIRO_PERIODO_FERIAS = src.CF_ADICIONAR_TERCEIRO_PERIODO_FERIAS,
    CF_CONVERSATION_ID = src.CF_CONVERSATION_ID, CF_HSM_DATA = src.CF_HSM_DATA,
    CF_HSM_DESCRICAO_TEMPLATE = src.CF_HSM_DESCRICAO_TEMPLATE, CF_HSM_STATUS = src.CF_HSM_STATUS,
    CF_HSM_TEMPLATE = src.CF_HSM_TEMPLATE, CF_WHATSAPP_ID = src.CF_WHATSAPP_ID,
    CF_MIGRACAO_DE_AREA = src.CF_MIGRACAO_DE_AREA, CF_TAG_DE_ATENDIMENTO_3 = src.CF_TAG_DE_ATENDIMENTO_3,
    CF_RENOVOU_CERTIFICADO_ECNPJ = src.CF_RENOVOU_CERTIFICADO_ECNPJ,
    CF_ATRIBUICAO_AUTOMATICA = src.CF_ATRIBUICAO_AUTOMATICA, CF_PIECE_OF_CAKE_DISPARO = src.CF_PIECE_OF_CAKE_DISPARO,
    CUSTOM_FIELDS_JSON = src.CUSTOM_FIELDS_JSON,
    REOPENS = src.REOPENS, REPLIES = src.REPLIES,
    ASSIGNEE_STATIONS = src.ASSIGNEE_STATIONS, GROUP_STATIONS = src.GROUP_STATIONS,
    AGENT_WAIT_TIME_IN_MINUTES = src.AGENT_WAIT_TIME_IN_MINUTES,
    REQUESTER_WAIT_TIME_IN_MINUTES = src.REQUESTER_WAIT_TIME_IN_MINUTES,
    FIRST_RESOLUTION_TIME_IN_MINUTES = src.FIRST_RESOLUTION_TIME_IN_MINUTES,
    FULL_RESOLUTION_TIME_IN_MINUTES = src.FULL_RESOLUTION_TIME_IN_MINUTES,
    ON_HOLD_TIME_IN_MINUTES = src.ON_HOLD_TIME_IN_MINUTES, REPLY_TIME_IN_MINUTES = src.REPLY_TIME_IN_MINUTES,
    ASSIGNED_AT = src.ASSIGNED_AT, INITIALLY_ASSIGNED_AT = src.INITIALLY_ASSIGNED_AT,
    SOLVED_AT = src.SOLVED_AT, LATEST_COMMENT_ADDED_AT = src.LATEST_COMMENT_ADDED_AT,
    CREATED_AT = src.CREATED_AT, UPDATED_AT = src.UPDATED_AT,
    DATALAKE_UPDATED_AT = src.DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT = src._SNOWFLAKE_LOADED_AT

  WHEN NOT MATCHED THEN INSERT (
    ID, SUBJECT, STATUS, PRIORITY, BRAND_ID, ASSIGNEE_ID, REQUESTER_ID,
    SUBMITTER_ID, ORGANIZATION_ID, GROUP_ID, TICKET_FORM_ID, VIA, TAGS,
    SATISFACTION_RATING, IS_PUBLIC, HAS_INCIDENTS, FROM_MESSAGING_CHANNEL,
    CF_ACIONAR_CONTABILIDADE, CF_MOTIVO_DE_CONTATO, CF_TAG_DE_ATENDIMENTO, CF_TAG_DE_ATENDIMENTO_2,
    CF_ADICIONAR_SEGUNDO_PERIODO_FERIAS, CF_ADICIONAR_TERCEIRO_PERIODO_FERIAS,
    CF_CONVERSATION_ID, CF_HSM_DATA, CF_HSM_DESCRICAO_TEMPLATE, CF_HSM_STATUS, CF_HSM_TEMPLATE,
    CF_WHATSAPP_ID, CF_MIGRACAO_DE_AREA, CF_TAG_DE_ATENDIMENTO_3, CF_RENOVOU_CERTIFICADO_ECNPJ,
    CF_ATRIBUICAO_AUTOMATICA, CF_PIECE_OF_CAKE_DISPARO, CUSTOM_FIELDS_JSON,
    REOPENS, REPLIES, ASSIGNEE_STATIONS, GROUP_STATIONS,
    AGENT_WAIT_TIME_IN_MINUTES, REQUESTER_WAIT_TIME_IN_MINUTES,
    FIRST_RESOLUTION_TIME_IN_MINUTES, FULL_RESOLUTION_TIME_IN_MINUTES,
    ON_HOLD_TIME_IN_MINUTES, REPLY_TIME_IN_MINUTES,
    ASSIGNED_AT, INITIALLY_ASSIGNED_AT, SOLVED_AT, LATEST_COMMENT_ADDED_AT,
    CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT)
  VALUES (
    src.ID, src.SUBJECT, src.STATUS, src.PRIORITY, src.BRAND_ID, src.ASSIGNEE_ID, src.REQUESTER_ID,
    src.SUBMITTER_ID, src.ORGANIZATION_ID, src.GROUP_ID, src.TICKET_FORM_ID, src.VIA, src.TAGS,
    src.SATISFACTION_RATING, src.IS_PUBLIC, src.HAS_INCIDENTS, src.FROM_MESSAGING_CHANNEL,
    src.CF_ACIONAR_CONTABILIDADE, src.CF_MOTIVO_DE_CONTATO, src.CF_TAG_DE_ATENDIMENTO, src.CF_TAG_DE_ATENDIMENTO_2,
    src.CF_ADICIONAR_SEGUNDO_PERIODO_FERIAS, src.CF_ADICIONAR_TERCEIRO_PERIODO_FERIAS,
    src.CF_CONVERSATION_ID, src.CF_HSM_DATA, src.CF_HSM_DESCRICAO_TEMPLATE, src.CF_HSM_STATUS, src.CF_HSM_TEMPLATE,
    src.CF_WHATSAPP_ID, src.CF_MIGRACAO_DE_AREA, src.CF_TAG_DE_ATENDIMENTO_3, src.CF_RENOVOU_CERTIFICADO_ECNPJ,
    src.CF_ATRIBUICAO_AUTOMATICA, src.CF_PIECE_OF_CAKE_DISPARO, src.CUSTOM_FIELDS_JSON,
    src.REOPENS, src.REPLIES, src.ASSIGNEE_STATIONS, src.GROUP_STATIONS,
    src.AGENT_WAIT_TIME_IN_MINUTES, src.REQUESTER_WAIT_TIME_IN_MINUTES,
    src.FIRST_RESOLUTION_TIME_IN_MINUTES, src.FULL_RESOLUTION_TIME_IN_MINUTES,
    src.ON_HOLD_TIME_IN_MINUTES, src.REPLY_TIME_IN_MINUTES,
    src.ASSIGNED_AT, src.INITIALLY_ASSIGNED_AT, src.SOLVED_AT, src.LATEST_COMMENT_ADDED_AT,
    src.CREATED_AT, src.UPDATED_AT, src.DATALAKE_UPDATED_AT, src._SNOWFLAKE_LOADED_AT);

  RETURN 'CX.GOLD.ZENDESK_TICKETS carregado com sucesso em ' || CURRENT_TIMESTAMP()::STRING;
END;
$$;

-- ------------------------------------------------------------
-- 2.2 Users (sem NAME, sem EMAIL)
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CX.GOLD.ZENDESK_USERS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CX.GOLD.ZENDESK_USERS tgt
  USING (
    SELECT ID, ROLE, LOCALE, TIME_ZONE, TAGS, ACTIVE, VERIFIED, SUSPENDED, MODERATOR,
           RESTRICTED_AGENT, SHARED, SHARED_AGENT, TICKET_RESTRICTION,
           CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT
    FROM CX.SILVER.ZENDESK_USERS WHERE ID IS NOT NULL
  ) src ON tgt.ID = src.ID

  WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
    ROLE = src.ROLE, LOCALE = src.LOCALE, TIME_ZONE = src.TIME_ZONE, TAGS = src.TAGS,
    ACTIVE = src.ACTIVE, VERIFIED = src.VERIFIED, SUSPENDED = src.SUSPENDED, MODERATOR = src.MODERATOR,
    RESTRICTED_AGENT = src.RESTRICTED_AGENT, SHARED = src.SHARED, SHARED_AGENT = src.SHARED_AGENT,
    TICKET_RESTRICTION = src.TICKET_RESTRICTION, CREATED_AT = src.CREATED_AT, UPDATED_AT = src.UPDATED_AT,
    DATALAKE_UPDATED_AT = src.DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT = src._SNOWFLAKE_LOADED_AT

  WHEN NOT MATCHED THEN INSERT (ID, ROLE, LOCALE, TIME_ZONE, TAGS, ACTIVE, VERIFIED, SUSPENDED, MODERATOR,
    RESTRICTED_AGENT, SHARED, SHARED_AGENT, TICKET_RESTRICTION, CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT)
  VALUES (src.ID, src.ROLE, src.LOCALE, src.TIME_ZONE, src.TAGS, src.ACTIVE, src.VERIFIED, src.SUSPENDED, src.MODERATOR,
    src.RESTRICTED_AGENT, src.SHARED, src.SHARED_AGENT, src.TICKET_RESTRICTION, src.CREATED_AT, src.UPDATED_AT, src.DATALAKE_UPDATED_AT, src._SNOWFLAKE_LOADED_AT);

  RETURN 'CX.GOLD.ZENDESK_USERS carregado com sucesso em ' || CURRENT_TIMESTAMP()::STRING;
END;
$$;

-- ============================================================
-- 3. EXTENSÕES: TICKETS_EVENTS, GROUPS, USERS.EXTERNAL_ID,
--    VIEW ZENDESK_AGENTS, SEED ZENDESK_BRANDS
-- ============================================================

-- ------------------------------------------------------------
-- 3.1 ZENDESK_TICKETS_EVENTS
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_TICKETS_EVENTS (
  ID                   NUMBER,
  TICKET_ID            NUMBER,
  FIELD_NAME           STRING,
  VALUE                STRING,
  AUTHOR_ID            NUMBER,
  CREATED_AT           TIMESTAMP_NTZ,
  DATALAKE_UPDATED_AT  TIMESTAMP_NTZ,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE PROCEDURE CX.GOLD.ZENDESK_TICKETS_EVENTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CX.GOLD.ZENDESK_TICKETS_EVENTS tgt
  USING (
    SELECT ID, TICKET_ID, FIELD_NAME, VALUE, AUTHOR_ID, CREATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT
    FROM CX.SILVER.ZENDESK_TICKETS_EVENTS WHERE ID IS NOT NULL
  ) src
    ON tgt.ID = src.ID AND COALESCE(tgt.FIELD_NAME, '') = COALESCE(src.FIELD_NAME, '')
  WHEN MATCHED THEN UPDATE SET
    TICKET_ID = src.TICKET_ID, VALUE = src.VALUE,
    AUTHOR_ID = src.AUTHOR_ID, CREATED_AT = src.CREATED_AT,
    DATALAKE_UPDATED_AT = src.DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT = src._SNOWFLAKE_LOADED_AT
  WHEN NOT MATCHED THEN INSERT (ID, TICKET_ID, FIELD_NAME, VALUE, AUTHOR_ID, CREATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT)
  VALUES (src.ID, src.TICKET_ID, src.FIELD_NAME, src.VALUE, src.AUTHOR_ID, src.CREATED_AT, src.DATALAKE_UPDATED_AT, src._SNOWFLAKE_LOADED_AT);

  RETURN 'CX.GOLD.ZENDESK_TICKETS_EVENTS carregado com sucesso em ' || CURRENT_TIMESTAMP()::STRING;
END;
$$;

-- ------------------------------------------------------------
-- 3.2 ZENDESK_GROUPS
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_GROUPS (
  ID                   NUMBER,
  NAME                 STRING,
  DESCRIPTION          STRING,
  IS_DEFAULT           BOOLEAN,
  DELETED              BOOLEAN,
  CREATED_AT           TIMESTAMP_NTZ,
  UPDATED_AT           TIMESTAMP_NTZ,
  DATALAKE_UPDATED_AT  TIMESTAMP_NTZ,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE PROCEDURE CX.GOLD.ZENDESK_GROUPS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CX.GOLD.ZENDESK_GROUPS tgt
  USING (
    SELECT ID, NAME, DESCRIPTION, IS_DEFAULT, DELETED, CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT
    FROM CX.SILVER.ZENDESK_GROUPS WHERE ID IS NOT NULL
  ) src ON tgt.ID = src.ID
  WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
    NAME = src.NAME, DESCRIPTION = src.DESCRIPTION, IS_DEFAULT = src.IS_DEFAULT, DELETED = src.DELETED,
    CREATED_AT = src.CREATED_AT, UPDATED_AT = src.UPDATED_AT,
    DATALAKE_UPDATED_AT = src.DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT = src._SNOWFLAKE_LOADED_AT
  WHEN NOT MATCHED THEN INSERT (ID, NAME, DESCRIPTION, IS_DEFAULT, DELETED, CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT)
  VALUES (src.ID, src.NAME, src.DESCRIPTION, src.IS_DEFAULT, src.DELETED, src.CREATED_AT, src.UPDATED_AT, src.DATALAKE_UPDATED_AT, src._SNOWFLAKE_LOADED_AT);

  RETURN 'CX.GOLD.ZENDESK_GROUPS carregado com sucesso em ' || CURRENT_TIMESTAMP()::STRING;
END;
$$;

-- ------------------------------------------------------------
-- 3.3 USERS: adicionar EXTERNAL_ID (não-PII) + atualizar procedure
-- ------------------------------------------------------------
ALTER TABLE CX.GOLD.ZENDESK_USERS
  ADD COLUMN IF NOT EXISTS EXTERNAL_ID STRING;

CREATE OR REPLACE PROCEDURE CX.GOLD.ZENDESK_USERS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CX.GOLD.ZENDESK_USERS tgt
  USING (
    SELECT ID, ROLE, LOCALE, TIME_ZONE, TAGS, ACTIVE, VERIFIED, SUSPENDED, MODERATOR,
           RESTRICTED_AGENT, SHARED, SHARED_AGENT, TICKET_RESTRICTION, EXTERNAL_ID,
           CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT
    FROM CX.SILVER.ZENDESK_USERS WHERE ID IS NOT NULL
  ) src ON tgt.ID = src.ID

  WHEN MATCHED AND src.UPDATED_AT > tgt.UPDATED_AT THEN UPDATE SET
    ROLE = src.ROLE, LOCALE = src.LOCALE, TIME_ZONE = src.TIME_ZONE, TAGS = src.TAGS,
    ACTIVE = src.ACTIVE, VERIFIED = src.VERIFIED, SUSPENDED = src.SUSPENDED, MODERATOR = src.MODERATOR,
    RESTRICTED_AGENT = src.RESTRICTED_AGENT, SHARED = src.SHARED, SHARED_AGENT = src.SHARED_AGENT,
    TICKET_RESTRICTION = src.TICKET_RESTRICTION, EXTERNAL_ID = src.EXTERNAL_ID,
    CREATED_AT = src.CREATED_AT, UPDATED_AT = src.UPDATED_AT,
    DATALAKE_UPDATED_AT = src.DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT = src._SNOWFLAKE_LOADED_AT

  WHEN NOT MATCHED THEN INSERT (ID, ROLE, LOCALE, TIME_ZONE, TAGS, ACTIVE, VERIFIED, SUSPENDED, MODERATOR,
    RESTRICTED_AGENT, SHARED, SHARED_AGENT, TICKET_RESTRICTION, EXTERNAL_ID, CREATED_AT, UPDATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT)
  VALUES (src.ID, src.ROLE, src.LOCALE, src.TIME_ZONE, src.TAGS, src.ACTIVE, src.VERIFIED, src.SUSPENDED, src.MODERATOR,
    src.RESTRICTED_AGENT, src.SHARED, src.SHARED_AGENT, src.TICKET_RESTRICTION, src.EXTERNAL_ID,
    src.CREATED_AT, src.UPDATED_AT, src.DATALAKE_UPDATED_AT, src._SNOWFLAKE_LOADED_AT);

  RETURN 'CX.GOLD.ZENDESK_USERS carregado com sucesso em ' || CURRENT_TIMESTAMP()::STRING;
END;
$$;

-- ------------------------------------------------------------
-- 3.4 VIEW ZENDESK_AGENTS (Silver -> Gold com filtro ROLE='AGENT')
--     NAME aqui é nome de colaborador, não PII de cliente.
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW CX.GOLD.ZENDESK_AGENTS AS
SELECT ID, NAME, EXTERNAL_ID
FROM CX.SILVER.ZENDESK_USERS
WHERE ROLE = 'AGENT';

-- ------------------------------------------------------------
-- 3.5 SEED ZENDESK_BRANDS (mapa BRAND_ID -> nome legível)
-- ------------------------------------------------------------
CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_BRANDS (
  ID    NUMBER,
  NAME  STRING
) AS SELECT * FROM VALUES
  (34126647548180, '<YOUR_BRAND_NAME>'),
  (43696510017940, '<YOUR_BRAND_NAME>')
AS t(ID, NAME);

-- ------------------------------------------------------------
-- 3.6 TASK Gold atualizada (cascateada após Silver, a cada 6h)
-- ------------------------------------------------------------
CREATE OR REPLACE TASK CX.GOLD.TASK_ZENDESK_GOLD
  WAREHOUSE = WH_DATA_SERVICES
  SCHEDULE = 'USING CRON 40 */6 * * * America/Sao_Paulo'
AS
  BEGIN
    CALL CX.GOLD.ZENDESK_TICKETS();
    CALL CX.GOLD.ZENDESK_USERS();
    CALL CX.GOLD.ZENDESK_GROUPS();
    CALL CX.GOLD.ZENDESK_TICKETS_EVENTS();
  END;

ALTER TASK CX.GOLD.TASK_ZENDESK_GOLD RESUME;

-- ============================================================
-- 4. ZENDESK_TICKET_COMMENTS (metadados — SEM corpo/PII)
--    Body/html_body/plain_body NÃO são expostos na Gold por serem
--    PII de texto livre (ficam apenas na Silver, sob masking).
--    A Gold mantém só metadados úteis para análise agregada.
-- ============================================================

CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_TICKET_COMMENTS (
  ID                   NUMBER,
  AUDIT_ID             NUMBER,
  TICKET_ID            NUMBER,
  AUTHOR_ID            NUMBER,
  IS_PUBLIC            BOOLEAN,
  VIA                  STRING,
  TYPE                 STRING,
  CREATED_AT           TIMESTAMP_NTZ,
  DATALAKE_UPDATED_AT  TIMESTAMP_NTZ,
  _SNOWFLAKE_LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE PROCEDURE CX.GOLD.ZENDESK_TICKET_COMMENTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CX.GOLD.ZENDESK_TICKET_COMMENTS tgt
  USING (
    SELECT ID, AUDIT_ID, TICKET_ID, AUTHOR_ID, IS_PUBLIC, VIA, TYPE,
           CREATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT
    FROM CX.SILVER.ZENDESK_TICKET_COMMENTS WHERE ID IS NOT NULL
  ) src ON tgt.ID = src.ID
  WHEN MATCHED THEN UPDATE SET
    AUDIT_ID = src.AUDIT_ID, TICKET_ID = src.TICKET_ID, AUTHOR_ID = src.AUTHOR_ID,
    IS_PUBLIC = src.IS_PUBLIC, VIA = src.VIA, TYPE = src.TYPE,
    CREATED_AT = src.CREATED_AT, DATALAKE_UPDATED_AT = src.DATALAKE_UPDATED_AT,
    _SNOWFLAKE_LOADED_AT = src._SNOWFLAKE_LOADED_AT
  WHEN NOT MATCHED THEN INSERT (ID, AUDIT_ID, TICKET_ID, AUTHOR_ID, IS_PUBLIC, VIA, TYPE,
    CREATED_AT, DATALAKE_UPDATED_AT, _SNOWFLAKE_LOADED_AT)
  VALUES (src.ID, src.AUDIT_ID, src.TICKET_ID, src.AUTHOR_ID, src.IS_PUBLIC, src.VIA, src.TYPE,
    src.CREATED_AT, src.DATALAKE_UPDATED_AT, src._SNOWFLAKE_LOADED_AT);

  RETURN 'CX.GOLD.ZENDESK_TICKET_COMMENTS carregado com sucesso em ' || CURRENT_TIMESTAMP()::STRING;
END;
$$;

-- TASK Gold atualizada (inclui comments + agents names)
CREATE OR REPLACE TASK CX.GOLD.TASK_ZENDESK_GOLD
  WAREHOUSE = WH_DATA_SERVICES
  SCHEDULE = 'USING CRON 40 */6 * * * America/Sao_Paulo'
AS
  BEGIN
    CALL CX.GOLD.ZENDESK_TICKETS();
    CALL CX.GOLD.ZENDESK_USERS();
    CALL CX.GOLD.ZENDESK_GROUPS();
    CALL CX.GOLD.ZENDESK_TICKETS_EVENTS();
    CALL CX.GOLD.ZENDESK_TICKET_COMMENTS();
    CALL CX.GOLD.KPI_TICKETS();
    CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_AGENTS_NAMES AS
      SELECT ID, NAME, EXTERNAL_ID FROM CX.SILVER.ZENDESK_USERS WHERE ROLE = 'AGENT';
    GRANT SELECT ON TABLE CX.GOLD.ZENDESK_AGENTS_NAMES TO ROLE ROLE_DOMAIN_CX;
  END;

ALTER TASK CX.GOLD.TASK_ZENDESK_GOLD RESUME;

-- ============================================================
-- VIEW: Ticket Field Options (lê Bronze para expor opções de campos custom)
-- ============================================================
CREATE OR REPLACE VIEW CX.GOLD.ZENDESK_TICKET_FIELD_OPTIONS AS
SELECT DISTINCT
    tf.RAW_DATA:id::BIGINT AS FIELD_ID,
    tf.RAW_DATA:title::STRING AS FIELD_TITLE,
    o.value:value::STRING AS OPTION_VALUE,
    o.value:name::STRING AS OPTION_LABEL
FROM WILD_CARD.BRONZE.ZENDESK_TICKET_FIELDS tf,
    LATERAL FLATTEN(input => PARSE_JSON(tf.RAW_DATA:custom_field_options)) o
WHERE tf.RAW_DATA:custom_field_options IS NOT NULL;

-- ============================================================
-- TABLE: Agents Names (nomes desmascarados para uso no Metabase)
-- ============================================================
CREATE OR REPLACE TABLE CX.GOLD.ZENDESK_AGENTS_NAMES AS
SELECT ID, NAME, EXTERNAL_ID
FROM CX.SILVER.ZENDESK_USERS
WHERE ROLE = 'AGENT';

GRANT SELECT ON TABLE CX.GOLD.ZENDESK_AGENTS_NAMES TO ROLE ROLE_DOMAIN_CX;
